micronaut:
  application:
    name: orange-talent-pix

  grpc:
    server:
      port: ${SERVER_PORT:50051}
      keep-alive-time: 1h
      max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5435/pix
    driverClassName: org.postgresql.Driver
    username: pix
    password: 123
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

values:
  erp-itau:
    host: ${ERP_ITAU_HOST:localhost}
    port: ${ERP_ITAU_PORT:9091}